AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template To Create a DynamoDB

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Source Email Address For SES.
        Parameters:
          - SourceEmailAddress

Parameters:
  SourceEmailAddress:
    Description: The name of the AWS environment
    Type: String
  HashKeyElementName:
    Type: String
    Default: key_name
    Description: Hash Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: Hash Key Type
Resources:
  FileRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "workflow-dynamoDB-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - 
          AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - 
          AttributeName: !Ref HashKeyElementName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Environment:
        Variables:
          DynamoDBTableName: !Sub "workflow-dynamoDB-${AWS::AccountId}-${AWS::Region}"
          SourceEmailAddress: !Sub "${SourceEmailAddress}"
          Region: !Sub "${AWS::Region}"
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Code:
        S3Bucket: !Sub "batch-${AWS::AccountId}-${AWS::Region}"
        S3Key: "index.zip"
      Runtime: nodejs14.x
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: FullAccessToDynamoDB
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:*
            Resource: arn:aws:dynamodb:*:*:*
          - Effect: Allow
            Action:
            - ses:SendEmail
            Resource: arn:aws:ses:*:*:*
          - Effect: Allow
            Action:
            - s3:*
            Resource: !Sub "arn:aws:s3:::batch-${AWS::AccountId}-${AWS::Region}/*"
Outputs:
  Employee:
    Description: Table Created using this template.
    Value: !Ref FileRecordsTable